### ISSUE TITLE
onCellContextMenu preventDefault still shows browser context menu.

### ISSUE THREAD

**Issue by ScarletJack** [glideapps/glide-data-grid#288]
Trying to add a right click menu to my implementation of the glide data grid and can't get the browser context menu not to show.

```tsx
onCellContextMenu={(e, y) => {
    y.preventDefault()
    ...
}}
```

Doesn't seem to do anything?

**Comment by jassmith** [comment]
Fixed in main

**Comment by sitch** [comment]
I'm on v4.2.1 and it still seems like an issue whether or not preventDefault is called...

**Comment by jassmith** [comment]
Do you experience issues here? https://glideapps.github.io/glide-data-grid/?path=/story/glide-data-grid-dataeditor-demos--header-menus Are you right clicking on a cell or a header?

**Comment by ScarletJack** [comment]
Issue persists when right clicking on any part of the grid on that storybook link. Using Chrome 103.0.5060.53

**Comment by jassmith** [comment]
This seems to be a mac specific issue. Your example works on my machine on windows but on mac the menu is not prevented.

**Comment by jassmith** [comment]
Okay I figured out the problem, the menu on MacOS comes up immediately on mouseDown but on windows it waits for mouse up. I will figure out a solution, this makes it non-trivial.

**Comment by sitch** [comment]
Im on arch linux & chrome with the issue

**Comment by ScarletJack** [comment]
Probably should've mentioned I'm on Ubuntu 😅

**Comment by jassmith** [comment]
Fixed in 5.0.0 for real this time
